FORMAT: 1A
HOST: foodcloseto.me/

# foodcloseto.me

foodcloseto.me is an app that allows people to search data about restaurants and see information about their location, reviews, and food type.

## Restaurants Collection [/API/Restaurants]

### List All Restaurants [GET]

+ Response 200 (API/Restaurants)

        [
            {
                "id": "2152",
                "name": "1431 Cafe",
                "yelp_id": "1431-cafe-cedar-park",
                "location": 78613,
                "lat": 30.5235192410157,
                "long": -97.8236986312133,
                "city": "Cedar Park",
                "address": "601 E Whitestone Blvd",
                "phone": "(512) 528-0018",
                "price": "$$",
                "rating": 3.0,
                "review": "This is a great place for breakfast. We haven't made it over here for the afternoon yet but this place is friendly and has some good home style cooking. The...",
                "review_date": "2016-12-26 20:32:23",
                "review_count": 187,
                "url": "https://www.yelp.com/biz/1431-cafe-cedar-park?adjust_creative=oQeTOrWw-rVtEKjG6sA2ew&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=oQeTOrWw-rVtEKjG6sA2ew",
                "img_url": "https://s3-media2.fl.yelpcdn.com/bphoto/0gsIQQCTGZgmthtOgknrAQ/o.jpg",
                "food_type": "tradamerican",
                "food_type2": "breakfast_brunch",
                "food_type3": null,
                "food_type_disp": "American (Traditional)",
                "food_type_disp2": "Breakfast & Brunch",
                "food_type_disp3": null
            },
            {
                ...
            },
            {
                ...
            }
        ]

## Restaurants filtering and sorting [/API/Restaurants{?sortby,rating,price,food_type,name}]

+ Parameters
    + sortby (optional) - A variable that specifies whether you want to sort by rating, price or name
    + rating (optional) - A variable that specifies whether you want to filter by rating: 1,2,3,4,5 (yelp stars dawg)
    + price (optional) - A variable that specifies whether you want to filter by price: "$", "$$"... "$$$$"
    + food_type (optional) - A variable that specifies whether you want to filter by food type: "American"
    + name (optional) - A variable that specifies whether you want to filter by name: "Los toros hermanos"
    <! example: http://foodcloseto.me/API/Restaurants?sortby=price&rating=2,3>
### filter and sort Restaurants [GET]

+ Response 200 (API/Restaurants)

        [
            {
                "id": "2152",
                "name": "1431 Cafe",
                "yelp_id": "1431-cafe-cedar-park",
                "location": 78613,
                "lat": 30.5235192410157,
                "long": -97.8236986312133,
                "city": "Cedar Park",
                "address": "601 E Whitestone Blvd",
                "phone": "(512) 528-0018",
                "price": "$$",
                "rating": 3.0,
                "review": "This is a great place for breakfast. We haven't made it over here for the afternoon yet but this place is friendly and has some good home style cooking. The...",
                "review_date": "2016-12-26 20:32:23",
                "review_count": 187,
                "url": "https://www.yelp.com/biz/1431-cafe-cedar-park?adjust_creative=oQeTOrWw-rVtEKjG6sA2ew&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=oQeTOrWw-rVtEKjG6sA2ew",
                "img_url": "https://s3-media2.fl.yelpcdn.com/bphoto/0gsIQQCTGZgmthtOgknrAQ/o.jpg",
                "food_type": "tradamerican",
                "food_type2": "breakfast_brunch",
                "food_type3": null,
                "food_type_disp": "American (Traditional)",
                "food_type_disp2": "Breakfast & Brunch",
                "food_type_disp3": null
            },
            {
                "address": "4221 South 1st", 
                "city": "Austin", 
                "food_type": "streetvendors", 
                "food_type2": null, 
                "food_type3": null, 
                "food_type_disp": "Street Vendors", 
                "food_type_disp2": null, 
                "food_type_disp3": null, 
                "id": "152", 
                "img_url": "/static/img/default.jpg", 
                "lat": 30.2234380346903, 
                "location": 78745, 
                "long": -97.771303653717, 
                "name": "Antojitos Mexicanos Truck", 
                "phone": "(512) 803-5099", 
                "price": "$$", 
                "rating": 2.0, 
                "review": "I recently read a list of the top 10 taco trucks in Austin.  As my gringo husband is obsessed with tacos, I shot him the list while he was at work. He...", 
                "review_count": 1, 
                "review_date": "2013-09-12 10:52:16", 
                "url": "https://www.yelp.com/biz/antojitos-mexicanos-truck-austin?adjust_creative=oQeTOrWw-rVtEKjG6sA2ew&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=oQeTOrWw-rVtEKjG6sA2ew", 
                "yelp_id": "antojitos-mexicanos-truck-austin"
              }, 
            {
                ...
            }
        ]

## Reviews Collection [/API/Reviews]

### List All Reviews [GET]

+ Response 200 (API/Reviews)

        [
            {
               "id": 3235,
                "restaurant_id": "2220",
                "restaurant_name": "Jack in the Box",
                "yelp_restaurant_id": "jack-in-the-box-round-rock-4",
                "food_type": "hotdogs",
                "food_type_disp": "Fast Food",
                "date": "2016-12-30 00:12:14",
                "rating": 1,
                "username": "'Karina G.",
                "review": "The worst customer service ever! Crystal took my order and forgot to give me half my order. I waited 15 minutes only at the window and 5 minutes at the...",
                "profile_picture_url": "https://s3-media4.fl.yelpcdn.com/photo/AQmT5rsbsZHaqUSe4ho0Gw/o.jpg",
                "review_url": "https://www.yelp.com/biz/jack-in-the-box-round-rock-4?hrid=dIaRjMnLAHeFv1DTBB1UVw&adjust_creative=oQeTOrWw-rVtEKjG6sA2ew&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=oQeTOrWw-rVtEKjG6sA2ew",
                "zipcode": 78681
            },
            {
            ...
            },
            {
            ...
            }
        ]

## Locations Collection [/API/Locations]

### List All Locations [GET]

+ Response 200 (API/Locations)

        [
            {
                "zipcode": 73301,
                "average_rating": 4.83,
                "average_price": 1.0,
                "highest_price": "$",
                "lowest_price": "$",
                "popular_food_type": "restaurants",
                "highest_rated_restaurant": 46,
                "most_popular_restaurant": "1689",
                "number_restaurants": 3
            },
            {
                ...
            },
            {
                ...
            }
        ]
        
## Food Types Collection [/Food_Types]

### List All Food Types [GET]

+ Response 200 (API/Food_Types)

        [
            {
                "food_type": "acaibowls",
                "food_type_display_name": "Acai Bowls",
                "average_price": 2.0,
                "average_rating": 4.5,
                "image_url": "/static/img/acaibowls.jpg",
                "number_restaurants": 1,
                "most_popular_restaurant": "1035",
                "highest_rated_restaurant": "1035",
                "best_location": "78746"
            },
            {
                ...
            },
            {
                ...
            }
        ]